CREATE TABLE employee_detail (
    "EMP_ID"            NUMBER(3, 0) NOT NULL,
    "FULL_NAME"         VARCHAR2(30 BYTE) NOT NULL,
    "MANAGER_ID"        NUMBER(3, 0),
    "DATE_OF_JOINING"   DATE NOT NULL,
    CONSTRAINT "EMP_ID_PK" PRIMARY KEY ( "EMP_ID" )
)

CREATE TABLE employee_salary (
    "EMP_ID"    NUMBER(3, 0) NOT NULL,
    "PROJECT"   VARCHAR2(2 BYTE) NOT NULL,
    "SALARY"    NUMBER(7, 0),
    CONSTRAINT "EMP_ID_FK" FOREIGN KEY ( "EMP_ID" )
        REFERENCES employee_detail ( "EMP_ID" )
)

Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (986,'Amit Gupta',null,to_date('2016-04-12','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (342,'Anu Rao',null,to_date('1982-01-01','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (344,'Aman Kumar Mishra',null,to_date('1982-01-01','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (321,'Watter White',986,to_date('2015-01-30','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (503,'Salja Singh Panwar',344,to_date('2012-08-17','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (876,'Sita Jha',503,to_date('2014-01-01','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (421,'Kuldeep Singh Rana',876,to_date('2016-11-27','YYYY-MM-DD'));
Insert into EMPLOYEE_DETAIL (EMP_ID,FULL_NAME,MANAGER_ID,DATE_OF_JOINING) values (121,'John Snow',321,to_date('2014-01-31','YYYY-MM-DD'));


Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (121,'P1',8000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (321,'P1',null);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (421,'P2',34000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (421,'P3',34000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (421,'P1',34000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (503,'P3',25000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (986,'P4',37000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (503,'P3',25000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (503,'P1',40000);
Insert into EMPLOYEE_SALARY (EMP_ID,PROJECT,SALARY) values (321,'P3',70000);